import { Product } from "@/components/ProductCard";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Premium Sterling Silver Ring",
    slug: "premium-sterling-silver-ring",
    price: 1299,
    originalPrice: 1999,
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600&q=80",
    rating: 4.8,
    reviewsCount: 38,
    isBestseller: true,
    category: "rings",
    gender: "women",
    occasion: "everyday",
    color: "sterling-silver",
    description: "Indulge in the timeless charm of this classic 92.5% Sterling Silver Ring. Styled with detailed hand-craftsmanship and a brilliant shine, it sits comfortably as a statement or wedding companion.",
    material: "925 Sterling Silver",
    sizes: ["12", "14", "16", "18"]
  },
  {
    id: "prod-2",
    name: "Royal Gold Plated Necklace",
    slug: "royal-gold-plated-necklace",
    price: 2499,
    originalPrice: 3499,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80",
    rating: 4.9,
    reviewsCount: 54,
    isBestseller: true,
    category: "necklaces",
    gender: "women",
    occasion: "wedding",
    color: "gold-plated",
    description: "A gorgeous 18K gold plated necklace with antique engravings. Its premium weight and majestic patterns replicate royal bridal designs, adding an aura of tradition to festive wardrobes.",
    material: "18K Gold Plated Brass",
    sizes: ["One Size"]
  },
  {
    id: "prod-3",
    name: "Elegant Rose Gold Bracelet",
    slug: "elegant-rose-gold-bracelet",
    price: 1899,
    originalPrice: 2699,
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1611085583191-a3b1a30a5a40?w=600&q=80",
    rating: 4.7,
    reviewsCount: 29,
    isBestseller: false,
    category: "bracelets",
    gender: "women",
    occasion: "office",
    color: "rose-gold",
    description: "Designed for subtle glamour, this Rose Gold Bracelet merges delicate chain lines with smooth geometric loops. Ideal for corporate daily wear or high-end evening dinners.",
    material: "Rose Gold Plated Silver",
    sizes: ["S", "M", "L"]
  },
  {
    id: "prod-4",
    name: "Oxidized Silver Jhumkas",
    slug: "oxidized-silver-jhumkas",
    price: 899,
    originalPrice: 1299,
    image: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1629224316810-9d8805b95e76?w=600&q=80",
    rating: 4.6,
    reviewsCount: 71,
    isBestseller: true,
    category: "earrings",
    gender: "women",
    occasion: "festive",
    color: "oxidised-silver",
    description: "Featuring a rich antique dark wash and intricate floral engravings, these Oxidized Jhumkas provide a stellar ethnic vibe. Made lightweight for day-long festive comfort.",
    material: "Oxidized Alloy and Silver",
    sizes: ["One Size"]
  },
  {
    id: "prod-5",
    name: "Solitaire Engagement Ring",
    slug: "solitaire-engagement-ring",
    price: 4999,
    originalPrice: 6999,
    image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&q=80",
    rating: 5.0,
    reviewsCount: 16,
    isBestseller: false,
    category: "rings",
    gender: "women",
    occasion: "wedding",
    color: "sterling-silver",
    description: "A breathtaking solitaire ring hosting a brilliant cushion-cut Swiss Zirconia stone on a premium sterling silver band. The perfect symbol of your lifelong commitment.",
    material: "925 Sterling Silver & Swiss Zirconia",
    sizes: ["10", "12", "14", "16"]
  },
  {
    id: "prod-6",
    name: "Men Sterling Silver Kada",
    slug: "men-silver-kada",
    price: 3599,
    originalPrice: 4999,
    image: "https://images.unsplash.com/photo-1611085583191-a3b1a30a5a40?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80",
    rating: 4.9,
    reviewsCount: 42,
    isBestseller: true,
    category: "kada",
    gender: "men",
    occasion: "everyday",
    color: "sterling-silver",
    description: "A sleek, heavy-weight kada tailored for men. Features smooth curved edges, high-polish finish, and durable 92.5% silver build that highlights strength and elegance.",
    material: "925 Sterling Silver",
    sizes: ["2.4", "2.6", "2.8"]
  },
  {
    id: "prod-7",
    name: "Butterfly Silver Pendant",
    slug: "butterfly-silver-pendant",
    price: 1599,
    originalPrice: 2199,
    image: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    rating: 4.5,
    reviewsCount: 19,
    isBestseller: false,
    category: "pendants",
    gender: "kids",
    occasion: "gift",
    color: "sterling-silver",
    description: "A cute, whimsical butterfly pendant decorated with miniature colorful enamel accents. Extremely gentle on skin, adjustable clasp chain included.",
    material: "925 Sterling Silver & Enamel",
    sizes: ["Adjustable"]
  },
  {
    id: "prod-8",
    name: "Minimalist Silver Anklet",
    slug: "minimalist-silver-anklet",
    price: 999,
    originalPrice: 1499,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80",
    rating: 4.6,
    reviewsCount: 31,
    isBestseller: false,
    category: "anklets",
    gender: "women",
    occasion: "everyday",
    color: "sterling-silver",
    description: "Add a soft shimmer to your stride with this double-layered silver anklet, styled with polished silver drop beads and a sturdy spring clasp.",
    material: "925 Sterling Silver",
    sizes: ["Free Size"]
  }
];
